FROM quay.io/centos/centos:stream10
RUN curl -L https://trunk.rdoproject.org/centos10-master/dlrn-deps.repo -o /etc/yum.repos.d/dlrn-deps.repo
RUN dnf update -y && \
    dnf install -y 'dnf-command(config-manager)' && \
    dnf config-manager --set-enabled crb && \
    dnf install -y \
        python3-pip \
	python3-devel \
	jq && \
    python3 -m pip install yq && \
    dnf install -y $(yq -r '.packages | join(" ")' /tmp/rpms.in.yaml) && \
    dnf clean all
# pip_find_builddeps comes from https://github.com/containerbuildsystem/cachi2/blob/main/docs/pip.md#requirements-buildtxt
RUN curl -L https://raw.githubusercontent.com/containerbuildsystem/cachito/master/bin/pip_find_builddeps.py -o /usr/bin/pip_find_builddeps && chmod u+x /usr/bin/pip_find_builddeps
RUN python3 -m pip install -U pip && pip install pip-tools
RUN cat /tmp/cachi2.env >> $HOME/.bashrc
